import Head from "next/head";
import { Container, FormControl, Row, Col, Card } from "react-bootstrap";
import { useState } from "react";
import axios from "axios";
import { useQuery } from "react-query";
import Link from 'next/link'

const getPokemon = async (params) => {
  const { data } = await axios.get(`/api/search?q=${params?.queryKey}`);
  return data.map((pokemon) => ({
    ...pokemon,
    image: `/pokemon/${pokemon.name.english
      .toLowerCase()
      .replace(" ", "-")}.jpg`,
  }));
};

export default function Poke() {
  const [query, setQuery] = useState("");
  const { data } = useQuery(query, getPokemon);

  return (
    <div>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <FormControl
          placeholder="Search"
          aria-label="Search"
          value={query}
          onChange={(e) => {
            setQuery(e.target.value);
          }}
        />
        {data && (
          <Row style={{ marginTop: 30 }}>
            {data.map(({ id, name, type, image }) => (
              <Col xs={4} key={id} style={{ padding: 5 }}>
                <Link href={`/pokemon/${name.english}`}>
                  <Card>
                    <Card.Img
                      variant="top"
                      src={image}
                      style={{ maxHeight: 300, minHeight: 300 }}
                    />
                    <Card.Body>
                      <Card.Title>{name.english}</Card.Title>
                      <Card.Subtitle>{type.join(", ")}</Card.Subtitle>
                    </Card.Body>
                  </Card>
                </Link>
              </Col>
            ))}
          </Row>
        )}
      </Container>
    </div>
  );
}
