import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Container,   FormControl} from 'react-bootstrap'
import { useState } from 'react';
import axios from 'axios'
import {QueryClient, QueryClientProvider, useQuery} from 'react-query'
import Poke from '../component/Poke';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Poke />
    </div>
  )
}
